\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest}{}\section{gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test Class Reference}
\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest}\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test}}


Inheritance diagram for gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=234pt]{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest__inherit__graph}
\end{center}
\end{figure}


Collaboration diagram for gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test\+:\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=234pt]{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest__coll__graph}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a7d02a890df0e3990aa107288c21f7dc7}{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a3fe17da71b72c1693fa358f71c6b31be}{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a8e791760b553d92490005deea0812f44}{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a56c906c34e689ee016ab1bf14fe5220c}{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a6451307941e063bcc3927992c1f2df54}{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a40ba50bf018753b7b21ed93ed60e4e1c}{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ac73b336590a3d1c242124e9ea5464a42}{test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a922cb0b598034924c19e6695cc9f7513}{test\+Catches\+Non\+Std\+Cxx\+Exceptions} (self)
\item 
def \hyperlink{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_af3a794d5af0b3d72789293531468050a}{test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program} (self)
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\begin{DoxyVerb}Tests C++ exception-catching behavior.

   Tests in this test case verify that:
   * C++ exceptions are caught and logged as C++ (not SEH) exceptions
   * Exception thrown affect the remainder of the test work flow in the
     expected manner.
\end{DoxyVerb}
 

\subsection{Member Function Documentation}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor@{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor@{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor(self)}{testCatchesCxxExceptionsInFixtureConstructor(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Constructor (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a7d02a890df0e3990aa107288c21f7dc7}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a7d02a890df0e3990aa107288c21f7dc7}

\begin{DoxyCode}
123   \textcolor{keyword}{def }testCatchesCxxExceptionsInFixtureConstructor(self):
124     self.assert\_(\textcolor{stringliteral}{'C++ exception with description '}
125                  \textcolor{stringliteral}{'"Standard C++ exception" thrown '}
126                  \textcolor{stringliteral}{'in the test fixture\(\backslash\)'s constructor'}
127                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
128     self.assert\_(\textcolor{stringliteral}{'unexpected'} \textcolor{keywordflow}{not} \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT,
129                  \textcolor{stringliteral}{'This failure belongs in this test only if '}
130                  \textcolor{stringliteral}{'"CxxExceptionInConstructorTest" (no quotes) '}
131                  \textcolor{stringliteral}{'appears on the same line as words "called unexpectedly"'})
132 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor@{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor@{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor(self)}{testCatchesCxxExceptionsInFixtureDestructor(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Fixture\+Destructor (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a3fe17da71b72c1693fa358f71c6b31be}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a3fe17da71b72c1693fa358f71c6b31be}

\begin{DoxyCode}
136     \textcolor{keyword}{def }testCatchesCxxExceptionsInFixtureDestructor(self):
137       self.assert\_(\textcolor{stringliteral}{'C++ exception with description '}
138                    \textcolor{stringliteral}{'"Standard C++ exception" thrown '}
139                    \textcolor{stringliteral}{'in the test fixture\(\backslash\)'s destructor'}
140                    \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
141       self.assert\_(\textcolor{stringliteral}{'CxxExceptionInDestructorTest::TearDownTestCase() '}
142                    \textcolor{stringliteral}{'called as expected.'}
143                    \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
144 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up@{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up@{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up(self)}{testCatchesCxxExceptionsInSetUp(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a6451307941e063bcc3927992c1f2df54}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a6451307941e063bcc3927992c1f2df54}

\begin{DoxyCode}
173   \textcolor{keyword}{def }testCatchesCxxExceptionsInSetUp(self):
174     self.assert\_(\textcolor{stringliteral}{'C++ exception with description "Standard C++ exception"'}
175                  \textcolor{stringliteral}{' thrown in SetUp()'}
176                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
177     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTest::TearDownTestCase() '}
178                  \textcolor{stringliteral}{'called as expected.'}
179                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
180     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTest destructor '}
181                  \textcolor{stringliteral}{'called as expected.'}
182                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
183     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTest::TearDown() '}
184                  \textcolor{stringliteral}{'called as expected.'}
185                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
186     self.assert\_(\textcolor{stringliteral}{'unexpected'} \textcolor{keywordflow}{not} \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT,
187                  \textcolor{stringliteral}{'This failure belongs in this test only if '}
188                  \textcolor{stringliteral}{'"CxxExceptionInSetUpTest" (no quotes) '}
189                  \textcolor{stringliteral}{'appears on the same line as words "called unexpectedly"'})
190 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case@{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case@{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case(self)}{testCatchesCxxExceptionsInSetUpTestCase(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Set\+Up\+Test\+Case (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a8e791760b553d92490005deea0812f44}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a8e791760b553d92490005deea0812f44}

\begin{DoxyCode}
145   \textcolor{keyword}{def }testCatchesCxxExceptionsInSetUpTestCase(self):
146     self.assert\_(\textcolor{stringliteral}{'C++ exception with description "Standard C++ exception"'}
147                  \textcolor{stringliteral}{' thrown in SetUpTestCase()'}
148                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
149     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInConstructorTest::TearDownTestCase() '}
150                  \textcolor{stringliteral}{'called as expected.'}
151                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
152     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTestCaseTest constructor '}
153                  \textcolor{stringliteral}{'called as expected.'}
154                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
155     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTestCaseTest destructor '}
156                  \textcolor{stringliteral}{'called as expected.'}
157                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
158     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTestCaseTest::SetUp() '}
159                  \textcolor{stringliteral}{'called as expected.'}
160                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
161     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTestCaseTest::TearDown() '}
162                  \textcolor{stringliteral}{'called as expected.'}
163                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
164     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInSetUpTestCaseTest test body '}
165                  \textcolor{stringliteral}{'called as expected.'}
166                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
167 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down@{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down@{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down(self)}{testCatchesCxxExceptionsInTearDown(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a40ba50bf018753b7b21ed93ed60e4e1c}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a40ba50bf018753b7b21ed93ed60e4e1c}

\begin{DoxyCode}
191   \textcolor{keyword}{def }testCatchesCxxExceptionsInTearDown(self):
192     self.assert\_(\textcolor{stringliteral}{'C++ exception with description "Standard C++ exception"'}
193                  \textcolor{stringliteral}{' thrown in TearDown()'}
194                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
195     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInTearDownTest::TearDownTestCase() '}
196                  \textcolor{stringliteral}{'called as expected.'}
197                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
198     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInTearDownTest destructor '}
199                  \textcolor{stringliteral}{'called as expected.'}
200                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
201 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case@{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case@{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case(self)}{testCatchesCxxExceptionsInTearDownTestCase(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Tear\+Down\+Test\+Case (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a56c906c34e689ee016ab1bf14fe5220c}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a56c906c34e689ee016ab1bf14fe5220c}

\begin{DoxyCode}
168   \textcolor{keyword}{def }testCatchesCxxExceptionsInTearDownTestCase(self):
169     self.assert\_(\textcolor{stringliteral}{'C++ exception with description "Standard C++ exception"'}
170                  \textcolor{stringliteral}{' thrown in TearDownTestCase()'}
171                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
172 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body@{test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body}}
\index{test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body@{test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body(self)}{testCatchesCxxExceptionsInTestBody(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Cxx\+Exceptions\+In\+Test\+Body (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ac73b336590a3d1c242124e9ea5464a42}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_ac73b336590a3d1c242124e9ea5464a42}

\begin{DoxyCode}
202   \textcolor{keyword}{def }testCatchesCxxExceptionsInTestBody(self):
203     self.assert\_(\textcolor{stringliteral}{'C++ exception with description "Standard C++ exception"'}
204                  \textcolor{stringliteral}{' thrown in the test body'}
205                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
206     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInTestBodyTest::TearDownTestCase() '}
207                  \textcolor{stringliteral}{'called as expected.'}
208                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
209     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInTestBodyTest destructor '}
210                  \textcolor{stringliteral}{'called as expected.'}
211                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
212     self.assert\_(\textcolor{stringliteral}{'CxxExceptionInTestBodyTest::TearDown() '}
213                  \textcolor{stringliteral}{'called as expected.'}
214                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
215 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Catches\+Non\+Std\+Cxx\+Exceptions@{test\+Catches\+Non\+Std\+Cxx\+Exceptions}}
\index{test\+Catches\+Non\+Std\+Cxx\+Exceptions@{test\+Catches\+Non\+Std\+Cxx\+Exceptions}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Catches\+Non\+Std\+Cxx\+Exceptions(self)}{testCatchesNonStdCxxExceptions(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Catches\+Non\+Std\+Cxx\+Exceptions (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a922cb0b598034924c19e6695cc9f7513}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_a922cb0b598034924c19e6695cc9f7513}

\begin{DoxyCode}
216   \textcolor{keyword}{def }testCatchesNonStdCxxExceptions(self):
217     self.assert\_(\textcolor{stringliteral}{'Unknown C++ exception thrown in the test body'}
218                  \textcolor{keywordflow}{in} EX\_BINARY\_OUTPUT)
219 
\end{DoxyCode}
\index{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}!test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program@{test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program}}
\index{test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program@{test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program}!gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test@{gtest\+\_\+catch\+\_\+exceptions\+\_\+test\+::\+Catch\+Cxx\+Exceptions\+Test}}
\subsubsection[{\texorpdfstring{test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program(self)}{testUnhandledCxxExceptionsAbortTheProgram(self)}}]{\setlength{\rightskip}{0pt plus 5cm}def gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+Catch\+Cxx\+Exceptions\+Test.\+test\+Unhandled\+Cxx\+Exceptions\+Abort\+The\+Program (
\begin{DoxyParamCaption}
\item[{}]{self}
\end{DoxyParamCaption}
)}\hypertarget{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_af3a794d5af0b3d72789293531468050a}{}\label{classgtest__catch__exceptions__test_1_1CatchCxxExceptionsTest_af3a794d5af0b3d72789293531468050a}

\begin{DoxyCode}
220   \textcolor{keyword}{def }testUnhandledCxxExceptionsAbortTheProgram(self):
221     \textcolor{comment}{# Filters out SEH exception tests on Windows. Unhandled SEH exceptions}
222     \textcolor{comment}{# cause tests to show pop-up windows there.}
223     FITLER\_OUT\_SEH\_TESTS\_FLAG = FILTER\_FLAG + \textcolor{stringliteral}{'=-*Seh*'}
224     \textcolor{comment}{# By default, Google Test doesn't catch the exceptions.}
225     uncaught\_exceptions\_ex\_binary\_output = \hyperlink{classgtest__test__utils_1_1Subprocess}{gtest\_test\_utils.Subprocess}(
226         [EX\_EXE\_PATH,
227          NO\_CATCH\_EXCEPTIONS\_FLAG,
228          FITLER\_OUT\_SEH\_TESTS\_FLAG],
229         env=environ).output
230 
231     self.assert\_(\textcolor{stringliteral}{'Unhandled C++ exception terminating the program'}
232                  \textcolor{keywordflow}{in} uncaught\_exceptions\_ex\_binary\_output)
233     self.assert\_(\textcolor{stringliteral}{'unexpected'} \textcolor{keywordflow}{not} \textcolor{keywordflow}{in} uncaught\_exceptions\_ex\_binary\_output)
234 
235 
\end{DoxyCode}


The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
vendor/googletest/googletest/test/\hyperlink{gtest__catch__exceptions__test_8py}{gtest\+\_\+catch\+\_\+exceptions\+\_\+test.\+py}\end{DoxyCompactItemize}
